import { expect, test } from '@oclif/test';
import { resourcePath } from '../__tests__/test-utils';
import 'chai';

describe('typegen', () => {
  describe('output', () => {
    test
      .stdout()
      .command(['typegen', resourcePath('openapi.yml')])
      .it('generates import statements', (ctx) => {
        expect(ctx.stdout).to.match(/import type/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json')])
      .it('generates schemas', (ctx) => {
        expect(ctx.stdout).to.match(/Schemas/);
        expect(ctx.stdout).to.match(/Pet/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json')])
      .it('generates operation paths', (ctx) => {
        expect(ctx.stdout).to.match(/Paths/);
        expect(ctx.stdout).to.match(/Responses/);
        expect(ctx.stdout).to.match(/PetRes/);
        expect(ctx.stdout).to.match(/Parameters/);
        expect(ctx.stdout).to.match(/ListPetsRes/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json'), '--client'])
      .it('exports operation methods', (ctx) => {
        expect(ctx.stdout).to.match(/export interface OperationMethods/);
        expect(ctx.stdout).to.match(/getPets/);
        expect(ctx.stdout).to.match(/createPet/);
        expect(ctx.stdout).to.match(/getPetById/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json'), '--client'])
      .it('exports paths dictionary', (ctx) => {
        expect(ctx.stdout).to.match(/export interface PathsDictionary/);
        expect(ctx.stdout).to.match(/\/pets/);
        expect(ctx.stdout).to.match(/\/pets\/\{id\}/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json'), '--client'])
      .it('exports Client type', (ctx) => {
        expect(ctx.stdout).to.match(/export type Client/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json'), '--backend'])
      .it('exports Backend operations', (ctx) => {
        expect(ctx.stdout).to.match(/export interface Operations/);
        expect(ctx.stdout).to.match(/getPets/);
        expect(ctx.stdout).to.match(/createPet/);
        expect(ctx.stdout).to.match(/getPetById/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json'), '--backend'])
      .it('exports Backend types', (ctx) => {
        expect(ctx.stdout).to.match(/export type OperationContext/);
        expect(ctx.stdout).to.match(/export type OperationResponse/);
        expect(ctx.stdout).to.match(/export type OperationHandler/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json'), '-A'])
      .it('generates module level schema aliases', (ctx) => {
        expect(ctx.stdout).to.match(/export type Pet = Components.Schemas.Pet/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json'), '-b', '/* Generated by openapicmd */'])
      .it('adds file banner', (ctx) => {
        expect(ctx.stdout).to.match(/Generated by openapicmd/);
      });

    test
      .stdout()
      .command(['typegen', resourcePath('openapi.json'), '--client', '--backend'])
      .it('exports both client and backend', (ctx) => {
        expect(ctx.stdout).to.match(/export type Client/);
        expect(ctx.stdout).to.match(/export type OperationHandler/);
        expect(ctx.stdout).to.match(/export interface Operations/);
        expect(ctx.stdout).to.match(/export interface OperationMethods/);
      })
  });
});
